name = "bzhr-wr"
main = "worker.js"
compatibility_date = "2026-09-04"

[alias]
"chromium-bidi/lib/cjs/bidiMapper/BidiMapper" = "./empty.js"
"chromium-bidi/lib/cjs/cdp/CdpConnection" = "./empty.js"

[vars]
BROWSER_WS_ENDPOINT = "wss://your-remote-browser-service-url-here"
